language: objective-c
before_install:
  - gem install cocoapods
before_script:
  - export LANG=en_US.UTF-8
  - cd Example ; pod update ; cd ..
script: xctool -workspace Example/RPInstantAlphaDemo.xcworkspace -scheme RPInstantAlphaDemo build
